export const DEVICE_SHOW_SPINNER = 'DEVICE_SHOW_SPINNER'
export const DEVICE_HIDE_SPINNER = 'DEVICE_HIDE_SPINNER'

export const FETCH_STATUS = 'FETCH_STATUS'
export const FETCH_STATUS_SUCCESS = 'FETCH_STATUS_SUCCESS'

export const FETCH_PORTS_REQUEST = 'FETCH_PORTS_REQUEST'
export const FETCH_PORTS_SUCCESS = 'FETCH_PORTS_SUCCESS'

export const CONNECT_DEVICE = 'CONNECT_DEVICE'
export const DISCONNECT_DEVICE = 'DISCONNECT_DEVICE'

export const SET_FREQUENCY = 'SET_FREQUENCY'

export const RECEIVE_RSSI = 'RECEIVE_RSSI'
